[package]
name = "interval"
version = "0.1.0"
edition = "2021"

[dependencies]
rug = "1.27.0"

[build]
target = "x86_64-pc-windows-gnu"

[target.x86_64-pc-windows-gnu]
linker = "C:\\msys64\\mingw64\\bin\\gcc.exe"